// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:osborn_book/pdf/models/downloaded_pdf.dart';
import 'package:osborn_book/pdf/models/local_bookmark.dart';
import 'package:osborn_book/pdf/models/local_highlight.dart';
import 'package:osborn_book/pdf/models/local_note.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DownloadedPdfAdapter());
    registerAdapter(LocalBookmarkAdapter());
    registerAdapter(LocalHighlightAdapter());
    registerAdapter(LocalNoteAdapter());
    registerAdapter(PdfTextLineLocalAdapter());
  }
}
